import { io } from "socket.io-client";
import { AudioEngine } from "./audio.js";
import { ProjectKScene } from "./scene.js";
import { loadSave, patchSave, resetSave, getActiveDeck } from "./save.js";
import { CARDS, CARD_TYPES, STARTER_DECKS, getCard, getMaster } from "../../shared/cards.js";
import { createDuel, deckFromStarter, applyAction, sanitizeDuelForPlayer, validateDeck, mastersForSelect, getCardCounts, createPracticeOpponent } from "../../shared/rules.js";
import { chooseBotAction } from "../../shared/bot.js";

const SERVER_URL = import.meta.env.VITE_SERVER_URL || "http://localhost:3000";
const LORE = "The world was once swallowed by rifts of living darkness. When all hope faded, the first K-Cards appeared - living seals that could summon guardians, cast spells, and bind the chaos. Now every Cardbearer carries a deck, and every duel decides who can stand against the next shadow.";

export class ProjectKApp {
  constructor(root) { this.root = root; this.save = loadSave(); this.audio = new AudioEngine(this.save.settings); this.mode = "boot"; this.socket = null; this.socketId = null; this.onlineLobby = null; this.onlineState = null; this.localState = null; this.localPlayerId = "local-player"; this.botTimer = null; this.hubMoveAt = 0; this.editorDeck = null; this.libraryFilter = "all"; this.librarySearch = ""; this.timerInterval = null; }
  start() { this.root.innerHTML = `<div class="app-shell"><div class="scene-host" data-scene></div><div class="hud-shell"><header class="topbar"><button class="brand" data-action="hub" type="button">PROJECT K</button><div class="topbar-status"><span data-connection>offline</span><span data-fps hidden></span></div></header><main class="panel" data-panel></main><div class="toast-stack" data-toasts></div></div></div>`; this.panel = this.root.querySelector("[data-panel]"); this.connectionEl = this.root.querySelector("[data-connection]"); this.fpsEl = this.root.querySelector("[data-fps]"); this.toastRoot = this.root.querySelector("[data-toasts]"); this.scene = new ProjectKScene(this.root.querySelector("[data-scene]"), { onStation: (s) => this.handleStation(s), onMove: (p) => this.sendHubPosition(p), onFps: (fps) => this.updateFps(fps), getSensitivity: () => this.save.settings.mouseSensitivity, getSocketId: () => this.socketId }); this.scene.start(); this.bindGlobalEvents(); if (!this.save.player) this.renderOnboarding(); else { this.scene.setProfile(this.save.player); this.connect(); this.renderHub(); } }
  bindGlobalEvents() { this.root.addEventListener("click", (event) => { const button = event.target.closest("[data-action]"); if (!button) return; this.audio.play("click"); this.handleAction(button.dataset.action, button.dataset, event); }); this.root.addEventListener("change", (event) => { const t = event.target; if (t.matches("[data-select-active-deck]")) { this.save = patchSave(this.save, { selectedDeckId: t.value, activeCustomDeckId: null }); this.toast("Active starter deck changed."); } if (t.matches("[data-editor-master]")) { this.editorDeck.deckMasterId = t.value; this.renderEditor(false); } if (t.matches("[data-library-filter]")) { this.libraryFilter = t.value; this.renderLibrary(false); } if (t.matches("[data-editor-filter]")) { this.editorFilter = t.value; this.renderEditor(false); } }); this.root.addEventListener("input", (event) => { const t = event.target; if (t.matches("[data-library-search]")) { this.librarySearch = t.value; this.renderLibrary(false); } if (t.matches("[data-setting]")) this.updateSetting(t); if (t.matches("[data-editor-search]")) { this.editorSearch = t.value; this.renderEditor(false); } }); this.root.addEventListener("mouseover", (event) => { const cardEl = event.target.closest("[data-preview-card]"); if (cardEl) this.scene.setPreviewCard(getCard(cardEl.dataset.previewCard)); }); }
  handleAction(action, data, event) { if (action === "hub") this.renderHub(); if (action === "finish-onboarding") this.finishOnboarding(event); if (action === "online") this.renderOnline(); if (action === "create-room") this.createOnlineRoom(); if (action === "join-room") this.joinOnlineRoom(); if (action === "ready-room") this.readyOnlineRoom(data.ready !== "true"); if (action === "bot") this.renderBotSetup(); if (action === "start-bot") this.startBotDuel(data.difficulty || "normal", false); if (action === "tutorial") this.startBotDuel("easy", true); if (action === "editor") this.renderEditor(true); if (action === "library") this.renderLibrary(true); if (action === "patch") this.renderPatchNotes(); if (action === "settings") this.renderSettings(); if (action === "duel-action") this.sendDuelAction({ type: data.type, handIndex: Number(data.handIndex) }); if (action === "play-card") this.playCard(Number(data.handIndex)); if (action === "editor-add") this.editorAdd(data.cardId); if (action === "editor-remove") this.editorRemove(Number(data.index)); if (action === "editor-save") this.editorSave(); if (action === "editor-reset") this.editorReset(); if (action === "editor-use-starter") this.editorUseStarter(data.deckId); if (action === "reset-save") this.resetLocalSave(); if (action === "fullscreen") document.documentElement.requestFullscreen?.(); }
  connect() { if (this.socket) return; this.socket = io(SERVER_URL, { transports: ["websocket", "polling"] }); this.connectionEl.textContent = "connecting"; this.socket.on("connect", () => { this.socketId = this.socket.id; this.connectionEl.textContent = "online"; this.socket.emit("player:enter", { ...this.save.player, position: this.scene.getPosition() }); }); this.socket.on("disconnect", () => { this.connectionEl.textContent = "offline"; }); this.socket.on("hub:snapshot", ({ players }) => this.scene.setRemotePlayers(players || [])); this.socket.on("duel:lobby", (lobby) => { this.onlineLobby = lobby; if (this.mode === "online") this.renderOnline(false); }); this.socket.on("duel:state", ({ state }) => { this.onlineState = state; this.mode = "online"; this.scene.setMode("duel"); this.scene.setDuelState(state); this.renderDuel(state, "online"); }); }
  sendHubPosition(position) { if (!this.socket?.connected) return; const now = performance.now(); if (now - this.hubMoveAt < 180) return; this.hubMoveAt = now; this.socket.emit("hub:position", { position, state: this.mode }); }
  updateFps(fps) { this.fpsEl.hidden = !this.save.settings.showFps; this.fpsEl.textContent = `${fps} FPS`; }
  handleStation(station) { if (this.mode !== "hub") return; const prompt = this.panel.querySelector("[data-station-prompt]"); if (!prompt) return; prompt.innerHTML = station ? `<button class="primary" data-action="${station.id === "online" ? "online" : station.id}" type="button">Enter ${escapeHtml(station.name)}</button>` : ""; }
  finishOnboarding(event) { const form = event.target.closest("form") || this.panel.querySelector("form"); const name = form.querySelector("[name=name]").value.trim().slice(0, 18); const color = form.querySelector("[name=color]:checked")?.value || "#f97316"; const selectedDeckId = form.querySelector("[name=starterDeck]").value; if (!name) return this.toast("Enter a Cardbearer name."); const player = { name, color }; this.save = patchSave(this.save, { player, selectedDeckId }); this.scene.setProfile(player); this.connect(); this.renderHub(); }
  renderOnboarding() { this.mode = "onboarding"; this.scene.setMode("preview"); this.panel.innerHTML = `<section class="screen narrow"><h1>PROJECT K</h1><p class="lore">${LORE}</p><form class="setup-form"><label><span>Name</span><input name="name" maxlength="18" autocomplete="off" placeholder="Cardbearer" /></label><fieldset class="swatches"><legend>Color</legend>${["#f97316", "#06b6d4", "#22c55e", "#a855f7", "#f43f5e"].map((c, i) => `<label class="swatch" style="--swatch:${c}"><input type="radio" name="color" value="${c}" ${i === 0 ? "checked" : ""} /><span></span></label>`).join("")}</fieldset><label><span>Starter Deck</span><select name="starterDeck">${STARTER_DECKS.map((d) => `<option value="${d.id}">${d.name}</option>`).join("")}</select></label><button class="primary wide" data-action="finish-onboarding" type="button">Enter The Atrium</button></form></section>`; this.scene.setPreviewCard(getMaster(STARTER_DECKS[0].deckMasterId)); }
  renderHub() { this.mode = "hub"; this.clearTimers(); this.scene.setMode("hub"); this.scene.setProfile(this.save.player || { name: "Cardbearer", color: "#f97316" }); this.panel.innerHTML = `<section class="screen hub-screen"><div class="hub-title"><p>The Cardbearer Atrium</p><h1>${escapeHtml(this.save.player?.name || "Cardbearer")}</h1></div><nav class="mode-grid"><button data-action="online" type="button">Online Duel</button><button data-action="bot" type="button">Bot Duel</button><button data-action="editor" type="button">Deck Editor</button><button data-action="library" type="button">Card Library</button><button data-action="tutorial" type="button">Tutorial Duel</button><button data-action="patch" type="button">Patch Notes</button><button data-action="settings" type="button">Settings</button></nav><div class="station-prompt" data-station-prompt></div><div class="quick-stats"><strong>${escapeHtml(getActiveDeck(this.save).name)}</strong><span>${this.save.stats.wins} wins</span><span>${this.save.stats.duelsPlayed} duels</span></div></section>`; }
  renderOnline(rebuild = true) { this.mode = "online"; this.connect(); if (!this.onlineState) this.scene.setMode("hub"); const lobby = this.onlineLobby; this.panel.innerHTML = `<section class="screen"><div class="screen-head"><button class="icon-button" data-action="hub" type="button">Back</button><div><p>Online Duel</p><h1>${lobby ? `Room ${lobby.code}` : "Room Board"}</h1></div></div>${lobby ? this.renderLobbyMarkup(lobby) : `<div class="online-grid"><div class="tool-panel"><h2>Host</h2><p class="muted">Active deck: ${escapeHtml(getActiveDeck(this.save).name)}</p><button class="primary wide" data-action="create-room" type="button">Create Room</button></div><div class="tool-panel"><h2>Join</h2><input data-room-code maxlength="4" placeholder="CODE" /><button class="primary wide" data-action="join-room" type="button">Join Room</button></div></div>`}</section>`; if (this.onlineState && rebuild) this.renderDuel(this.onlineState, "online"); }
  renderLobbyMarkup(lobby) { const me = lobby.players.find((p) => p.id === this.socketId); return `<div class="lobby-layout"><div class="room-code">${lobby.code}</div><div class="player-list">${lobby.players.map((p) => `<div class="player-row"><span class="dot" style="--dot:${p.color}"></span><strong>${escapeHtml(p.name)}</strong><span>${p.ready ? "Ready" : "Choosing"}</span></div>`).join("")}</div><label><span>Deck</span><select data-select-active-deck>${STARTER_DECKS.map((d) => `<option value="${d.id}" ${d.id === this.save.selectedDeckId ? "selected" : ""}>${d.name}</option>`).join("")}</select></label><button class="primary wide" data-action="ready-room" data-ready="${me?.ready ? "true" : "false"}" type="button">${me?.ready ? "Unready" : "Ready"}</button></div>`; }
  createOnlineRoom() { this.socket.emit("duel:create", { ...this.save.player, deck: getActiveDeck(this.save) }, (r) => r?.ok ? this.toast(`Room ${r.code} created.`) : this.toast(r?.message || "Could not create room.")); }
  joinOnlineRoom() { const code = this.panel.querySelector("[data-room-code]")?.value.trim().toUpperCase(); if (!code) return this.toast("Enter a room code."); this.socket.emit("duel:join", { code, ...this.save.player, deck: getActiveDeck(this.save) }, (r) => r?.ok ? this.toast(`Joined ${r.code}.`) : this.toast(r?.message || "Could not join room.")); }
  readyOnlineRoom(ready) { this.socket.emit("duel:setDeck", { code: this.onlineLobby?.code, deck: getActiveDeck(this.save) }, () => this.socket.emit("duel:ready", { code: this.onlineLobby?.code, ready })); }
  renderBotSetup() { this.mode = "bot"; this.scene.setMode("preview"); this.scene.setPreviewCard(getMaster(getActiveDeck(this.save).deckMasterId)); this.panel.innerHTML = `<section class="screen narrow"><div class="screen-head"><button class="icon-button" data-action="hub" type="button">Back</button><div><p>Bot Duel</p><h1>${escapeHtml(getActiveDeck(this.save).name)}</h1></div></div><div class="difficulty-row"><button class="primary" data-action="start-bot" data-difficulty="easy" type="button">Easy</button><button class="primary" data-action="start-bot" data-difficulty="normal" type="button">Normal</button><button class="primary" data-action="start-bot" data-difficulty="hard" type="button">Hard</button></div><label><span>Starter Deck</span><select data-select-active-deck>${STARTER_DECKS.map((d) => `<option value="${d.id}" ${d.id === this.save.selectedDeckId ? "selected" : ""}>${d.name}</option>`).join("")}</select></label></section>`; }
  startBotDuel(difficulty = "normal", tutorial = false) { const botDeckId = difficulty === "hard" ? "ember-pride" : difficulty === "easy" ? "tidebound-circle" : "starshade-pact"; const bot = { ...createPracticeOpponent(), deck: deckFromStarter(botDeckId), name: tutorial ? "Tutorial Guide" : "Atrium Bot" }; this.localState = createDuel({ seed: `bot-${difficulty}-${Date.now()}`, players: [{ id: this.localPlayerId, name: this.save.player?.name || "Cardbearer", color: this.save.player?.color || "#f97316", deck: getActiveDeck(this.save) }, bot], turnSeconds: tutorial ? 999 : 0 }); this.botDifficulty = difficulty; this.mode = tutorial ? "tutorial" : "bot"; this.scene.setMode("duel"); this.renderDuel(sanitizeDuelForPlayer(this.localState, this.localPlayerId), "local"); }
  renderDuel(state, source) { this.scene.setMode("duel"); this.scene.setDuelState(state); const selfIndex = Math.max(0, state.players.findIndex((p) => Array.isArray(p.hand))); const self = state.players[selfIndex]; const foe = state.players[selfIndex === 0 ? 1 : 0]; const isTurn = state.legal?.isTurn; this.panel.innerHTML = `<section class="duel-screen"><div class="duel-top">${lifePanel(foe, "opponent")}<div class="turn-badge"><span>Turn ${state.turnNumber}</span><strong>${escapeHtml(state.players[state.current]?.name || "")}</strong><div class="turn-countdown" data-countdown></div></div>${lifePanel(self, "player")}</div><div class="monster-row">${monsterPanel(foe, "Opponent")}${monsterPanel(self, "You")}</div><div class="duel-actions"><button data-action="duel-action" data-type="activateMaster" ${!state.legal?.canActivateMaster ? "disabled" : ""} type="button">${escapeHtml(self.master?.abilityName || "Deck Master")}</button><button data-action="duel-action" data-type="attack" ${!state.legal?.canAttack ? "disabled" : ""} type="button">Attack</button><button data-action="duel-action" data-type="endTurn" ${!isTurn || state.winner ? "disabled" : ""} type="button">End Turn</button><button data-action="duel-action" data-type="surrender" ${state.winner ? "disabled" : ""} type="button">Surrender</button></div><div class="hand-row">${(self.hand || []).map((id, i) => cardButtonMarkup(getCard(id), i, state)).join("")}</div><aside class="log-panel"><strong>${state.winner ? `${state.winner.name} wins` : isTurn ? "Your move" : "Waiting"}</strong><div>${state.log.map((e) => `<p>${escapeHtml(e.text)}</p>`).join("")}</div></aside></section>`; this.startCountdown(state); if (state.winner) this.finishDuel(state); else if (source === "local") this.queueBotTurn(); }
  playCard(handIndex) { const state = this.onlineState || sanitizeDuelForPlayer(this.localState, this.localPlayerId); const self = state.players.find((p) => Array.isArray(p.hand)); const card = getCard(self?.hand?.[handIndex]); if (card) this.sendDuelAction({ type: card.type === CARD_TYPES.MONSTER ? "playMonster" : "playSpell", handIndex }); }
  sendDuelAction(action) { if (this.onlineState) { this.socket.emit("duel:action", { code: this.onlineLobby?.code, action }, (r) => { if (!r?.ok) this.toast(r?.message || "Action failed."); }); return; } if (!this.localState) return; const result = applyAction(this.localState, this.localPlayerId, action); if (!result.ok) return this.toast(result.message); this.audio.play(action.type === "attack" ? "attack" : action.type === "playSpell" ? "spell" : "play"); this.scene.flash(action.type === "attack" ? "damage" : action.type === "activateMaster" ? "master" : "spell"); this.renderDuel(sanitizeDuelForPlayer(this.localState, this.localPlayerId), "local"); }
  queueBotTurn() { clearTimeout(this.botTimer); if (!this.localState || this.localState.winner) return; if (this.localState.players[this.localState.current].id !== "bot") return; this.botTimer = setTimeout(() => { const action = chooseBotAction(this.localState, "bot", this.botDifficulty); if (action) applyAction(this.localState, "bot", action); this.renderDuel(sanitizeDuelForPlayer(this.localState, this.localPlayerId), "local"); }, this.save.settings.reducedMotion ? 80 : 550); }
  finishDuel(state) { if (this.lastWinnerId === state.winner?.playerId) return; this.lastWinnerId = state.winner?.playerId; const won = state.winner?.playerId === this.localPlayerId || state.winner?.playerId === this.socketId; this.audio.play(won ? "victory" : "defeat"); this.save = patchSave(this.save, { stats: { duelsPlayed: this.save.stats.duelsPlayed + 1, wins: this.save.stats.wins + (won ? 1 : 0), losses: this.save.stats.losses + (won ? 0 : 1), botWins: this.save.stats.botWins + (won && this.localState ? 1 : 0), onlineWins: this.save.stats.onlineWins + (won && this.onlineState ? 1 : 0) }, tutorialCompleted: this.mode === "tutorial" ? true : this.save.tutorialCompleted }); }
  renderEditor(reset = false) { this.mode = "editor"; this.scene.setMode("preview"); if (reset || !this.editorDeck) { const active = getActiveDeck(this.save); this.editorDeck = { id: active.id?.startsWith("custom-") ? active.id : `custom-${Date.now()}`, name: active.name || "Custom K-Deck", cardIds: [...active.cardIds], deckMasterId: active.deckMasterId }; this.editorFilter = "all"; this.editorSearch = ""; } const validation = validateDeck(this.editorDeck); const counts = getCardCounts(this.editorDeck.cardIds); const cards = CARDS.filter((card) => (this.editorFilter === "all" || card.type === this.editorFilter) && (!this.editorSearch || card.name.toLowerCase().includes(this.editorSearch.toLowerCase()))); this.panel.innerHTML = `<section class="screen editor-screen"><div class="screen-head"><button class="icon-button" data-action="hub" type="button">Back</button><div><p>Deck Editor</p><h1>${escapeHtml(this.editorDeck.name)}</h1></div></div><div class="editor-layout"><div class="tool-panel deck-build"><label><span>Deck Master</span><select data-editor-master>${mastersForSelect().map((m) => `<option value="${m.id}" ${m.id === this.editorDeck.deckMasterId ? "selected" : ""}>${m.name}</option>`).join("")}</select></label><div class="deck-slots">${this.editorDeck.cardIds.map((id, i) => `<button data-action="editor-remove" data-index="${i}" data-preview-card="${id}" type="button">${escapeHtml(getCard(id).name)}</button>`).join("")}</div><div class="validation ${validation.valid ? "ok" : "bad"}">${validation.valid ? "Legal deck" : validation.errors.map(escapeHtml).join(" ")}</div><div class="button-row"><button class="primary" data-action="editor-save" type="button">Save</button><button data-action="editor-reset" type="button">Reset</button></div><div class="starter-strip">${STARTER_DECKS.map((d) => `<button data-action="editor-use-starter" data-deck-id="${d.id}" type="button">${d.name}</button>`).join("")}</div></div><div class="library-column"><div class="filter-row"><input data-editor-search placeholder="Search" value="${escapeHtml(this.editorSearch || "")}" /><select data-editor-filter>${["all", CARD_TYPES.MONSTER, CARD_TYPES.SPELL].map((t) => `<option value="${t}" ${t === this.editorFilter ? "selected" : ""}>${t}</option>`).join("")}</select></div><div class="card-grid compact">${cards.map((card) => cardMarkup(card, `<button data-action="editor-add" data-card-id="${card.id}" ${(this.editorDeck.cardIds.length >= 10 || (counts[card.id] || 0) >= 2) ? "disabled" : ""} type="button">Add</button>`)).join("")}</div></div></div></section>`; this.scene.setPreviewCard(getMaster(this.editorDeck.deckMasterId)); }
  editorAdd(cardId) { if (this.editorDeck.cardIds.length >= 10) return this.toast("Deck is full."); const counts = getCardCounts(this.editorDeck.cardIds); if ((counts[cardId] || 0) >= 2) return this.toast("Only 2 copies allowed."); this.editorDeck.cardIds.push(cardId); this.renderEditor(false); }
  editorRemove(index) { this.editorDeck.cardIds.splice(index, 1); this.renderEditor(false); }
  editorSave() { const validation = validateDeck(this.editorDeck); if (!validation.valid) return this.toast(validation.errors[0]); const deck = { ...this.editorDeck, name: "Custom K-Deck" }; const customDecks = this.save.customDecks.filter((d) => d.id !== deck.id); customDecks.push(deck); this.save = patchSave(this.save, { customDecks, activeCustomDeckId: deck.id }); this.toast("Deck saved and set active."); this.renderEditor(false); }
  editorReset() { this.editorDeck = { ...deckFromStarter(this.save.selectedDeckId), id: `custom-${Date.now()}` }; this.renderEditor(false); }
  editorUseStarter(deckId) { this.editorDeck = { ...deckFromStarter(deckId), id: `custom-${Date.now()}` }; this.renderEditor(false); }
  renderLibrary(setMode = true) { this.mode = "library"; if (setMode) this.scene.setMode("preview"); const cards = CARDS.filter((card) => (this.libraryFilter === "all" || card.type === this.libraryFilter) && (!this.librarySearch || card.name.toLowerCase().includes(this.librarySearch.toLowerCase()))); this.panel.innerHTML = `<section class="screen library-screen"><div class="screen-head"><button class="icon-button" data-action="hub" type="button">Back</button><div><p>Card Library</p><h1>${cards.length} K-Cards</h1></div></div><div class="filter-row"><input data-library-search placeholder="Search" value="${escapeHtml(this.librarySearch)}" /><select data-library-filter>${["all", CARD_TYPES.MONSTER, CARD_TYPES.SPELL].map((t) => `<option value="${t}" ${t === this.libraryFilter ? "selected" : ""}>${t}</option>`).join("")}</select></div><div class="card-grid">${cards.map((card) => cardMarkup(card)).join("")}</div></section>`; this.scene.setPreviewCard(cards[0]); }
  renderPatchNotes() { this.mode = "patch"; this.scene.setMode("preview"); this.save = patchSave(this.save, { patchNotesSeen: true }); this.panel.innerHTML = `<section class="screen narrow"><div class="screen-head"><button class="icon-button" data-action="hub" type="button">Back</button><div><p>Version 0.1.0</p><h1>First Seal</h1></div></div><ul class="patch-list"><li>Added Project K prototype</li><li>Added 3D hub</li><li>Added online duels</li><li>Added four starter decks</li><li>Added Deck Master system</li><li>Added deck editor</li><li>Added bot duel</li><li>Added card library</li></ul></section>`; }
  renderSettings() { this.mode = "settings"; this.scene.setMode("preview"); const s = this.save.settings; this.panel.innerHTML = `<section class="screen narrow"><div class="screen-head"><button class="icon-button" data-action="hub" type="button">Back</button><div><p>Settings</p><h1>Project K</h1></div></div><div class="settings-list">${slider("masterVolume", "Master Volume", s.masterVolume, 0, 1, .05)}${slider("sfxVolume", "SFX Volume", s.sfxVolume, 0, 1, .05)}${slider("musicVolume", "Music Volume", s.musicVolume, 0, 1, .05)}${slider("mouseSensitivity", "Mouse Sensitivity", s.mouseSensitivity, .2, 1.5, .05)}<label><span>Graphics Quality</span><select data-setting="graphicsQuality">${["low", "balanced", "high"].map((v) => `<option value="${v}" ${v === s.graphicsQuality ? "selected" : ""}>${v}</option>`).join("")}</select></label>${toggle("reducedMotion", "Reduced Motion", s.reducedMotion)}${toggle("showFps", "Show FPS", s.showFps)}${toggle("colorblindIcons", "Colorblind Card Icons", s.colorblindIcons)}<button data-action="fullscreen" type="button">Fullscreen</button><button class="danger" data-action="reset-save" type="button">Reset Local Save</button></div></section>`; }
  updateSetting(t) { const key = t.dataset.setting; const raw = t.type === "checkbox" ? t.checked : t.value; const value = t.type === "range" ? Number(raw) : raw; this.save = patchSave(this.save, { settings: { [key]: value } }); this.audio.updateSettings(this.save.settings); this.updateFps(this.scene.fps); }
  resetLocalSave() { this.save = resetSave(); this.audio.updateSettings(this.save.settings); this.onlineLobby = null; this.onlineState = null; this.localState = null; this.renderOnboarding(); }
  startCountdown(state) { clearInterval(this.timerInterval); const target = this.panel.querySelector("[data-countdown]"); if (!target || !state.turnSeconds) return; const update = () => { target.textContent = `${Math.max(0, Math.ceil((state.turnEndsAt - Date.now()) / 1000))}s`; }; update(); this.timerInterval = setInterval(update, 250); }
  clearTimers() { clearTimeout(this.botTimer); clearInterval(this.timerInterval); this.localState = null; this.onlineState = null; this.lastWinnerId = null; }
  toast(message) { const toast = document.createElement("div"); toast.className = "toast"; toast.textContent = message; this.toastRoot.appendChild(toast); setTimeout(() => toast.remove(), 2600); }
}

function lifePanel(player, label) { const pct = Math.max(0, Math.min(100, (player.life / 4000) * 100)); return `<div class="life-panel ${label}"><span>${escapeHtml(player.name)}</span><strong>${player.life}</strong><div class="life-bar"><i style="width:${pct}%"></i></div><small>${player.deckCount} deck / ${player.handCount} hand / ${player.graveCount} discard</small><small>${escapeHtml(player.master?.name || "")}: ${Math.round(player.masterMeter)}%</small></div>`; }
function monsterPanel(player, title) { const m = player.activeMonster; return `<div class="monster-panel ${m ? "active" : ""}"><span>${title}</span>${m ? `<strong>${escapeHtml(m.name)}</strong><small>ATK ${m.attack} / DEF ${m.defense}</small>` : "<strong>Open Zone</strong><small>No active monster</small>"}<small>Shield ${player.shield}</small></div>`; }
function cardButtonMarkup(card, handIndex, state) { const playable = state.legal?.isTurn && ((card.type === CARD_TYPES.MONSTER && state.legal.canPlayMonster) || (card.type === CARD_TYPES.SPELL && state.legal.canPlaySpell)); return `<button class="hand-card ${playable ? "playable" : ""}" data-action="play-card" data-hand-index="${handIndex}" data-preview-card="${card.id}" ${!playable ? "disabled" : ""} type="button">${cardFace(card)}</button>`; }
function cardMarkup(card, action = "") { return `<article class="k-card" data-preview-card="${card.id}">${cardFace(card)}${action}</article>`; }
function cardFace(card) { return `<div class="card-art" style="--c1:${card.art.primary};--c2:${card.art.secondary}"><span>${escapeHtml(card.art.symbol || "*")}</span></div><div class="card-body"><strong>${escapeHtml(card.name)}</strong><small>${card.element} / ${card.rarity}</small><p>${escapeHtml(card.effect)}</p>${card.type === CARD_TYPES.MONSTER ? `<div class="statline"><b>ATK ${card.attack}</b><b>DEF ${card.defense}</b></div>` : ""}</div>`; }
function slider(key, label, value, min, max, step) { return `<label><span>${label}</span><input data-setting="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${value}" /></label>`; }
function toggle(key, label, checked) { return `<label class="toggle-row"><span>${label}</span><input data-setting="${key}" type="checkbox" ${checked ? "checked" : ""} /></label>`; }
function escapeHtml(value) { return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
