import * as THREE from "three";
import { CARD_TYPES, getCard } from "../../shared/cards.js";

const STATIONS = [
  { id: "online", name: "Online Room Board", x: -5.8, z: -3.5, color: "#38bdf8" },
  { id: "bot", name: "Bot Duel Table", x: -2.1, z: -5.4, color: "#f97316" },
  { id: "editor", name: "Deck Editor Station", x: 3.4, z: -4.6, color: "#22c55e" },
  { id: "library", name: "Card Library Station", x: 6.1, z: 0.2, color: "#a855f7" },
  { id: "tutorial", name: "Tutorial NPC", x: 2.5, z: 4.7, color: "#facc15" },
  { id: "patch", name: "Patch Notes Board", x: -4.5, z: 4.3, color: "#fb7185" }
];

export class ProjectKScene {
  constructor(host, callbacks = {}) { this.host = host; this.callbacks = callbacks; this.clock = new THREE.Clock(); this.keys = new Set(); this.player = { x: 0, y: 0, z: 2.8, ry: 0 }; this.profile = { name: "Cardbearer", color: "#f97316" }; this.remotePlayers = []; this.mode = "hub"; this.cameraYaw = Math.PI; this.cameraPitch = 0.45; this.pointerDown = false; this.lastPointer = { x: 0, y: 0 }; this.fps = 0; this.frameCounter = 0; this.frameTimer = 0; }
  start() { this.renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true }); this.renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2)); this.renderer.setSize(this.host.clientWidth, this.host.clientHeight); this.renderer.shadowMap.enabled = true; this.host.appendChild(this.renderer.domElement); this.labelLayer = document.createElement("div"); this.labelLayer.className = "world-label-layer"; this.host.appendChild(this.labelLayer); this.scene = new THREE.Scene(); this.scene.background = new THREE.Color("#07111f"); this.scene.fog = new THREE.Fog("#07111f", 12, 35); this.camera = new THREE.PerspectiveCamera(58, 1, 0.1, 100); this.scene.add(new THREE.HemisphereLight("#dbeafe", "#172033", 1.7)); const key = new THREE.DirectionalLight("#fef3c7", 1.9); key.position.set(5, 8, 3); key.castShadow = true; this.scene.add(key); this.hubGroup = new THREE.Group(); this.duelGroup = new THREE.Group(); this.previewGroup = new THREE.Group(); this.scene.add(this.hubGroup, this.duelGroup, this.previewGroup); this.buildHub(); this.buildDuelBoard(); this.buildPreviewStage(); this.setMode("hub"); this.bindEvents(); this.resize(); this.animationId = requestAnimationFrame(() => this.tick()); }
  destroy() { cancelAnimationFrame(this.animationId); window.removeEventListener("resize", this.resizeBound); window.removeEventListener("keydown", this.keyDownBound); window.removeEventListener("keyup", this.keyUpBound); }
  bindEvents() { this.resizeBound = () => this.resize(); this.keyDownBound = (e) => { if (["INPUT", "TEXTAREA", "SELECT"].includes(document.activeElement?.tagName)) return; this.keys.add(e.code); }; this.keyUpBound = (e) => this.keys.delete(e.code); window.addEventListener("resize", this.resizeBound); window.addEventListener("keydown", this.keyDownBound); window.addEventListener("keyup", this.keyUpBound); this.renderer.domElement.addEventListener("pointerdown", (e) => { this.pointerDown = true; this.lastPointer = { x: e.clientX, y: e.clientY }; }); window.addEventListener("pointerup", () => { this.pointerDown = false; }); window.addEventListener("pointermove", (e) => { if (!this.pointerDown) return; const sensitivity = this.callbacks.getSensitivity?.() ?? 0.75; this.cameraYaw -= (e.clientX - this.lastPointer.x) * 0.004 * sensitivity; this.cameraPitch = THREE.MathUtils.clamp(this.cameraPitch + (e.clientY - this.lastPointer.y) * 0.002 * sensitivity, 0.18, 1.05); this.lastPointer = { x: e.clientX, y: e.clientY }; }); }
  resize() { const width = Math.max(1, this.host.clientWidth); const height = Math.max(1, this.host.clientHeight); this.camera.aspect = width / height; this.camera.updateProjectionMatrix(); this.renderer.setSize(width, height); }
  setProfile(profile) { this.profile = profile; this.updateAvatarColor(); }
  setMode(mode) { this.mode = mode; this.hubGroup.visible = mode === "hub"; this.duelGroup.visible = mode === "duel"; this.previewGroup.visible = mode === "preview"; this.nearStation = null; this.labelLayer.innerHTML = ""; }
  setRemotePlayers(players) { this.remotePlayers = players.filter((p) => p.id !== this.callbacks.getSocketId?.()); this.syncRemoteMeshes(); }
  setDuelState(state) { this.duelState = state; this.rebuildDuelDynamic(); }
  setPreviewCard(card) { clearGroup(this.previewDynamic); if (!card) return; const mesh = card.abilityName ? createMasterMesh(card) : card.type === CARD_TYPES.MONSTER ? createMonsterMesh(card) : createSpellGlyph(card); mesh.position.set(0, 1.15, 0); this.previewDynamic.add(mesh); }
  getPosition() { return { ...this.player }; }
  flash(kind) { if (!this.duelPulse) return; this.duelPulse.material.color.set(kind === "damage" ? "#fb7185" : kind === "spell" ? "#a855f7" : "#facc15"); this.duelPulse.scale.setScalar(1.4); }
  buildHub() { const floor = new THREE.Mesh(new THREE.CylinderGeometry(9, 9, 0.35, 96), new THREE.MeshStandardMaterial({ color: "#102033", roughness: 0.8, metalness: 0.1 })); floor.receiveShadow = true; this.hubGroup.add(floor); const ring = new THREE.Mesh(new THREE.TorusGeometry(7.4, 0.04, 8, 96), new THREE.MeshStandardMaterial({ color: "#38bdf8", emissive: "#0e7490", emissiveIntensity: 1.2 })); ring.rotation.x = Math.PI / 2; ring.position.y = 0.22; this.hubGroup.add(ring); this.playerMesh = createAvatarMesh(this.profile.color); this.playerMesh.position.set(this.player.x, 0.25, this.player.z); this.hubGroup.add(this.playerMesh); this.remoteGroup = new THREE.Group(); this.hubGroup.add(this.remoteGroup); this.stationGroup = new THREE.Group(); for (const station of STATIONS) { const marker = createStationMesh(station); marker.position.set(station.x, 0.35, station.z); marker.userData.station = station; this.stationGroup.add(marker); } this.hubGroup.add(this.stationGroup); this.atriumCore = new THREE.Mesh(new THREE.OctahedronGeometry(0.8, 0), new THREE.MeshStandardMaterial({ color: "#f8fafc", emissive: "#38bdf8", emissiveIntensity: 0.9, roughness: 0.35, metalness: 0.15 })); this.atriumCore.position.set(0, 2.2, 0); this.hubGroup.add(this.atriumCore); }
  buildDuelBoard() { const table = new THREE.Mesh(new THREE.BoxGeometry(7.5, 0.28, 5.2), new THREE.MeshStandardMaterial({ color: "#182235", roughness: 0.62, metalness: 0.2 })); table.position.y = 0.4; this.duelGroup.add(table); const lane = new THREE.Mesh(new THREE.PlaneGeometry(6.6, 4.3), new THREE.MeshBasicMaterial({ color: "#38bdf8", transparent: true, opacity: 0.08 })); lane.rotation.x = -Math.PI / 2; lane.position.y = 0.56; this.duelGroup.add(lane); this.duelPulse = new THREE.Mesh(new THREE.TorusGeometry(1.15, 0.025, 8, 72), new THREE.MeshBasicMaterial({ color: "#facc15", transparent: true, opacity: 0.8 })); this.duelPulse.rotation.x = Math.PI / 2; this.duelPulse.position.y = 0.62; this.duelGroup.add(this.duelPulse); this.duelDynamic = new THREE.Group(); this.duelGroup.add(this.duelDynamic); }
  buildPreviewStage() { const base = new THREE.Mesh(new THREE.CylinderGeometry(1.4, 1.7, 0.2, 48), new THREE.MeshStandardMaterial({ color: "#111827", roughness: 0.55, metalness: 0.25 })); base.position.y = 0.1; this.previewGroup.add(base); this.previewDynamic = new THREE.Group(); this.previewGroup.add(this.previewDynamic); }
  updateAvatarColor() { this.playerMesh?.traverse((child) => { if (child.isMesh && child.userData.avatarPart === "body") child.material.color.set(this.profile.color); }); }
  syncRemoteMeshes() { clearGroup(this.remoteGroup); for (const remote of this.remotePlayers) { const mesh = createAvatarMesh(remote.color || "#94a3b8"); mesh.position.set(remote.position?.x || 0, 0.25, remote.position?.z || 0); mesh.rotation.y = remote.position?.ry || 0; mesh.userData.remoteId = remote.id; this.remoteGroup.add(mesh); } }
  rebuildDuelDynamic() { clearGroup(this.duelDynamic); if (!this.duelState?.players?.length) return; const ownIndex = Math.max(0, this.duelState.players.findIndex((p) => Array.isArray(p.hand))); this.duelState.players.forEach((player, index) => { const isSelf = index === ownIndex; const z = isSelf ? 1.55 : -1.55; const master = createMasterMesh(player.master); master.position.set(isSelf ? -2.75 : 2.75, 0.75, isSelf ? 2.25 : -2.25); master.scale.setScalar(player.masterAwake ? 1.25 : 0.9); this.duelDynamic.add(master); if (player.activeMonster) { const monster = createMonsterMesh(getCard(player.activeMonster.cardId), player.activeMonster); monster.position.set(0, 0.72, z); monster.rotation.y = isSelf ? 0 : Math.PI; this.duelDynamic.add(monster); } }); }
  tick() { const dt = Math.min(0.05, this.clock.getDelta()); this.frameCounter += 1; this.frameTimer += dt; if (this.frameTimer >= 0.5) { this.fps = Math.round(this.frameCounter / this.frameTimer); this.frameCounter = 0; this.frameTimer = 0; this.callbacks.onFps?.(this.fps); } if (this.mode === "hub") this.updateHub(dt); if (this.mode === "duel") this.updateDuel(dt); if (this.mode === "preview") this.updatePreview(dt); this.updateLabels(); this.renderer.render(this.scene, this.camera); this.animationId = requestAnimationFrame(() => this.tick()); }
  updateHub(dt) { const speed = this.keys.has("ShiftLeft") || this.keys.has("ShiftRight") ? 5.2 : 3.2; const forward = Number(this.keys.has("KeyW")) - Number(this.keys.has("KeyS")); const right = Number(this.keys.has("KeyD")) - Number(this.keys.has("KeyA")); if (forward || right) { const yaw = this.cameraYaw + Math.PI; const sin = Math.sin(yaw); const cos = Math.cos(yaw); this.player.x += (right * cos + forward * sin) * speed * dt; this.player.z += (-right * sin + forward * cos) * speed * dt; const len = Math.hypot(this.player.x, this.player.z); if (len > 7.4) { this.player.x = (this.player.x / len) * 7.4; this.player.z = (this.player.z / len) * 7.4; } this.player.ry = Math.atan2(right * cos + forward * sin, right * sin - forward * cos); this.callbacks.onMove?.(this.getPosition()); } this.playerMesh.position.set(this.player.x, 0.25, this.player.z); this.playerMesh.rotation.y = this.player.ry; this.atriumCore.rotation.y += dt * 0.6; this.stationGroup.children.forEach((station, i) => { station.rotation.y += dt * (0.3 + i * 0.02); station.position.y = 0.35 + Math.sin(performance.now() / 500 + i) * 0.06; }); const target = new THREE.Vector3(this.player.x, 1.2, this.player.z); const d = 7.5; this.camera.position.set(target.x + Math.sin(this.cameraYaw) * Math.cos(this.cameraPitch) * d, target.y + Math.sin(this.cameraPitch) * d, target.z + Math.cos(this.cameraYaw) * Math.cos(this.cameraPitch) * d); this.camera.lookAt(target); this.checkStationProximity(); }
  updateDuel(dt) { this.camera.position.lerp(new THREE.Vector3(0, 5.8, 6.4), 0.08); this.camera.lookAt(0, 0.3, 0); this.duelPulse.rotation.z += dt * 1.4; this.duelPulse.scale.lerp(new THREE.Vector3(1, 1, 1), 0.06); this.duelDynamic.children.forEach((child) => { if (child.userData.spin) child.rotation.y += dt * 0.7; }); }
  updatePreview(dt) { this.camera.position.lerp(new THREE.Vector3(0, 2.4, 4.4), 0.12); this.camera.lookAt(0, 0.9, 0); this.previewDynamic.rotation.y += dt * 0.75; }
  checkStationProximity() { let closest = null; let closestDistance = Infinity; for (const station of STATIONS) { const distance = Math.hypot(this.player.x - station.x, this.player.z - station.z); if (distance < closestDistance) { closestDistance = distance; closest = station; } } const next = closestDistance < 1.55 ? closest : null; if (next?.id !== this.nearStation?.id) { this.nearStation = next; this.callbacks.onStation?.(next); } }
  updateLabels() { if (this.mode !== "hub") return; const labels = [{ id: "self", name: this.profile.name, position: new THREE.Vector3(this.player.x, 1.75, this.player.z) }, ...this.remotePlayers.map((p) => ({ id: p.id, name: p.name, position: new THREE.Vector3(p.position?.x || 0, 1.75, p.position?.z || 0) })), ...STATIONS.map((s) => ({ id: `station-${s.id}`, name: s.name, position: new THREE.Vector3(s.x, 1.45, s.z) }))]; for (const label of labels) { let el = this.labelLayer.querySelector(`[data-label-id="${label.id}"]`); if (!el) { el = document.createElement("div"); el.className = label.id.startsWith("station") ? "world-label station-label" : "world-label"; el.dataset.labelId = label.id; el.textContent = label.name; this.labelLayer.appendChild(el); } const screen = label.position.clone().project(this.camera); const x = (screen.x * 0.5 + 0.5) * this.host.clientWidth; const y = (-screen.y * 0.5 + 0.5) * this.host.clientHeight; el.style.transform = `translate(-50%, -50%) translate(${x}px, ${y}px)`; el.style.opacity = screen.z > 1 ? "0" : "1"; } }
}

function createAvatarMesh(color) { const g = new THREE.Group(); const body = new THREE.Mesh(new THREE.CapsuleGeometry(0.26, 0.58, 4, 10), new THREE.MeshStandardMaterial({ color, roughness: 0.45, metalness: 0.1 })); body.userData.avatarPart = "body"; body.castShadow = true; body.position.y = 0.62; g.add(body); const head = new THREE.Mesh(new THREE.SphereGeometry(0.2, 16, 12), new THREE.MeshStandardMaterial({ color: "#f8fafc", roughness: 0.5 })); head.position.y = 1.15; g.add(head); const card = new THREE.Mesh(new THREE.BoxGeometry(0.28, 0.38, 0.035), new THREE.MeshStandardMaterial({ color: "#0f172a", emissive: color, emissiveIntensity: 0.6 })); card.position.set(0.28, 0.82, 0.1); card.rotation.z = -0.25; g.add(card); return g; }
function createStationMesh(station) { const g = new THREE.Group(); g.add(new THREE.Mesh(new THREE.CylinderGeometry(0.56, 0.72, 0.16, 32), new THREE.MeshStandardMaterial({ color: "#111827", roughness: 0.4, metalness: 0.3 }))); const glyph = new THREE.Mesh(new THREE.OctahedronGeometry(0.34, 0), new THREE.MeshStandardMaterial({ color: station.color, emissive: station.color, emissiveIntensity: 0.9, roughness: 0.3 })); glyph.position.y = 0.62; glyph.userData.spin = true; g.add(glyph); return g; }
function createMonsterMesh(card, instance = null) { const g = new THREE.Group(); const primary = card?.model?.color || card?.art?.primary || "#38bdf8"; const accent = card?.model?.accent || card?.art?.secondary || "#f8fafc"; const mat = new THREE.MeshStandardMaterial({ color: primary, roughness: 0.42, metalness: 0.1 }); const acc = new THREE.MeshStandardMaterial({ color: accent, emissive: accent, emissiveIntensity: 0.35, roughness: 0.35 }); const attackScale = instance ? THREE.MathUtils.clamp(instance.attack / 1200, 0.75, 1.35) : 1; const defenseScale = instance ? THREE.MathUtils.clamp(instance.defense / 1400, 0.75, 1.3) : 1; const body = new THREE.Mesh(new THREE.DodecahedronGeometry(0.48 * defenseScale, 0), mat); body.scale.x = attackScale; g.add(body); const head = new THREE.Mesh(new THREE.SphereGeometry(0.24, 18, 14), acc); head.position.set(0, 0.42, 0.34); g.add(head); const crest = new THREE.Mesh(new THREE.ConeGeometry(0.16, 0.45, 5), acc); crest.position.set(0, 0.78, 0.1); g.add(crest); g.userData.spin = true; return g; }
function createMasterMesh(master) { const g = new THREE.Group(); const color = master?.model?.color || "#64748b"; const accent = master?.model?.accent || "#f8fafc"; g.add(new THREE.Mesh(new THREE.SphereGeometry(0.38, 18, 14), new THREE.MeshStandardMaterial({ color, emissive: color, emissiveIntensity: 0.35, roughness: 0.4 }))); const crown = new THREE.Mesh(new THREE.TorusKnotGeometry(0.24, 0.045, 48, 8), new THREE.MeshStandardMaterial({ color: accent, emissive: accent, emissiveIntensity: 0.45 })); crown.position.y = 0.42; g.add(crown); g.userData.spin = true; return g; }
function createSpellGlyph(card) { const g = new THREE.Group(); g.add(new THREE.Mesh(new THREE.TorusGeometry(0.52, 0.035, 8, 48), new THREE.MeshStandardMaterial({ color: card?.art?.primary || "#a855f7", emissive: card?.art?.primary || "#a855f7", emissiveIntensity: 0.75 }))); g.add(new THREE.Mesh(new THREE.OctahedronGeometry(0.28, 0), new THREE.MeshStandardMaterial({ color: card?.art?.secondary || "#f8fafc", emissive: card?.art?.secondary || "#f8fafc", emissiveIntensity: 0.45 }))); g.userData.spin = true; return g; }
function clearGroup(group) { if (!group) return; while (group.children.length) { const child = group.children.pop(); child.traverse?.((node) => { node.geometry?.dispose?.(); if (Array.isArray(node.material)) node.material.forEach((m) => m.dispose?.()); else node.material?.dispose?.(); }); } }
