import { CARD_BY_ID, CARD_TYPES, DECK_MASTERS, MASTER_BY_ID, STARTER_DECKS, getCard, getMaster, getStarterDeck } from "./cards.js";

export const DUEL_CONSTANTS = Object.freeze({ life: 4000, deckSize: 10, startingHand: 4, maxCopies: 2, minMonsters: 5, minSpells: 3, turnSeconds: 60, maxLog: 80 });
export const makeSeed = (label = "project-k") => `${label}-${Date.now()}-${Math.floor(Math.random() * 1000000)}`;
export function hashSeed(text) { let h = 2166136261; for (let i = 0; i < text.length; i += 1) { h ^= text.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }
export function seededRandom(seed) { let t = hashSeed(String(seed)); return () => { t += 0x6d2b79f5; let x = t; x = Math.imul(x ^ (x >>> 15), x | 1); x ^= x + Math.imul(x ^ (x >>> 7), x | 61); return ((x ^ (x >>> 14)) >>> 0) / 4294967296; }; }
export function shuffleWithSeed(items, seed) { const next = [...items]; const random = seededRandom(seed); for (let i = next.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [next[i], next[j]] = [next[j], next[i]]; } return next; }
export const cloneState = (value) => JSON.parse(JSON.stringify(value));

export function deckFromStarter(starterId) { const starter = getStarterDeck(starterId); return { name: starter.name, cardIds: [...starter.cardIds], deckMasterId: starter.deckMasterId }; }
export function getDeckOptions(customDecks = []) { return [...STARTER_DECKS.map((deck) => ({ ...deck, cardIds: [...deck.cardIds], source: "starter" })), ...customDecks.map((deck) => ({ ...deck, source: "custom" }))]; }

export function validateDeck(deck) {
  const errors = []; const cardIds = Array.isArray(deck?.cardIds) ? deck.cardIds : []; const counts = new Map(); let monsters = 0; let spells = 0;
  if (!MASTER_BY_ID[deck?.deckMasterId]) errors.push("Choose exactly 1 Deck Master.");
  if (cardIds.length !== DUEL_CONSTANTS.deckSize) errors.push("Deck must contain exactly 10 cards.");
  for (const id of cardIds) { const card = CARD_BY_ID[id]; if (!card) { errors.push(`Unknown card: ${id}`); continue; } counts.set(id, (counts.get(id) ?? 0) + 1); if (card.type === CARD_TYPES.MONSTER) monsters += 1; if (card.type === CARD_TYPES.SPELL) spells += 1; }
  for (const [id, count] of counts.entries()) if (count > DUEL_CONSTANTS.maxCopies) errors.push(`No more than 2 copies of ${CARD_BY_ID[id]?.name ?? id}.`);
  if (monsters < DUEL_CONSTANTS.minMonsters) errors.push("Deck must include at least 5 monsters.");
  if (spells < DUEL_CONSTANTS.minSpells) errors.push("Deck must include at least 3 spells.");
  return { valid: errors.length === 0, errors, counts: { monsters, spells, total: cardIds.length } };
}

function makePlayer(input, index, seed) {
  const fallback = STARTER_DECKS[index % STARTER_DECKS.length]; const suppliedDeck = input.deck ?? deckFromStarter(input.starterDeckId ?? fallback.id); const deck = validateDeck(suppliedDeck).valid ? suppliedDeck : deckFromStarter(fallback.id);
  return { id: input.id, name: input.name || `Cardbearer ${index + 1}`, color: input.color || ["#f97316", "#06b6d4", "#84cc16", "#a855f7"][index % 4], life: DUEL_CONSTANTS.life, deckMasterId: deck.deckMasterId, deck: shuffleWithSeed(deck.cardIds, `${seed}-p${index}`), hand: [], grave: [], activeMonster: null, monsterPlayed: false, spellPlayed: false, attacked: false, shield: 0, skipMonsterPlay: false, skipAttack: false, masterMeter: 0, masterAwake: false, masterUsed: false, stats: { damageDealt: 0, damageTaken: 0, healedPrevented: 0, monsterSurvivedAttacks: 0, spellsSeen: 0, turnsSurvived: 0 }, deckName: deck.name || fallback.name, connected: true };
}

export function createDuel({ players, seed = makeSeed("duel"), turnSeconds = DUEL_CONSTANTS.turnSeconds }) {
  const state = { id: seed, seed, status: "active", turnNumber: 1, current: 0, turnSeconds, turnEndsAt: Date.now() + turnSeconds * 1000, players: players.map((p, i) => makePlayer(p, i, seed)), log: [], winner: null, surrenderedBy: null };
  for (let i = 0; i < state.players.length; i += 1) drawCards(state, i, DUEL_CONSTANTS.startingHand, { initial: true });
  addLog(state, "The first K-Cards flare awake. Duel start."); beginTurn(state); return state;
}

export function addLog(state, text) { state.log.push({ id: `${Date.now()}-${state.log.length}`, text, at: Date.now() }); if (state.log.length > DUEL_CONSTANTS.maxLog) state.log.shift(); }
export const currentPlayer = (state) => state.players[state.current];
export const opponentIndex = (_state, playerIndex) => (playerIndex === 0 ? 1 : 0);
export const getPlayerIndex = (state, playerId) => state.players.findIndex((p) => p.id === playerId);
const actionOk = (state, message = "OK") => ({ ok: true, message, state });
const actionError = (message) => ({ ok: false, message });
function addMeter(player, amount) { player.masterMeter = Math.max(0, Math.min(100, player.masterMeter + amount)); }
function makeMonsterInstance(card, turnNumber) { return { uid: `${card.id}-${turnNumber}-${Math.floor(Math.random() * 100000)}`, cardId: card.id, attack: card.attack, defense: card.defense, baseAttack: card.attack, baseDefense: card.defense, summonedTurn: turnNumber, temporaryAttack: 0, temporaryDefense: 0 }; }
function resetTemporaryBuffs(player) { if (!player.activeMonster) return; player.activeMonster.attack -= player.activeMonster.temporaryAttack; player.activeMonster.defense -= player.activeMonster.temporaryDefense; player.activeMonster.temporaryAttack = 0; player.activeMonster.temporaryDefense = 0; }

export function beginTurn(state) { if (state.winner) return; const player = currentPlayer(state); resetTemporaryBuffs(player); player.monsterPlayed = false; player.spellPlayed = false; player.attacked = false; state.turnEndsAt = Date.now() + state.turnSeconds * 1000; addMeter(player, 8); if (!drawCards(state, state.current, 1).ok) return; addLog(state, `${player.name}'s turn begins.`); checkAllAwaken(state); }
export function endTurn(state, playerId = currentPlayer(state).id) { if (state.winner) return actionError("Duel is already over."); if (currentPlayer(state).id !== playerId) return actionError("It is not your turn."); const player = currentPlayer(state); resetTemporaryBuffs(player); player.stats.turnsSurvived += 1; addMeter(player, 8); state.current = opponentIndex(state, state.current); state.turnNumber += 1; beginTurn(state); return actionOk(state, "Turn ended."); }
export function drawCards(state, playerIndex, count = 1, options = {}) { const player = state.players[playerIndex]; for (let i = 0; i < count; i += 1) { if (player.deck.length === 0) { setWinner(state, opponentIndex(state, playerIndex), `${player.name} could not draw a card.`); return actionError("Deck empty."); } player.hand.push(player.deck.shift()); } if (!options.initial) addLog(state, `${player.name} draws ${count} card${count === 1 ? "" : "s"}.`); return actionOk(state, "Cards drawn."); }

export function applyAction(state, playerId, action) { if (state.winner && action.type !== "reset") return actionError("Duel is already over."); const playerIndex = getPlayerIndex(state, playerId); if (playerIndex === -1) return actionError("Unknown player."); if (action.type === "playMonster") return playMonster(state, playerIndex, action.handIndex); if (action.type === "playSpell") return playSpell(state, playerIndex, action.handIndex); if (action.type === "attack") return attack(state, playerIndex); if (action.type === "activateMaster") return activateDeckMaster(state, playerIndex); if (action.type === "endTurn") return endTurn(state, playerId); if (action.type === "surrender") return surrender(state, playerIndex); return actionError("Unknown action."); }
function requireTurn(state, playerIndex) { return state.current !== playerIndex ? actionError("It is not your turn.") : null; }

export function playMonster(state, playerIndex, handIndex) { const turnError = requireTurn(state, playerIndex); if (turnError) return turnError; const player = state.players[playerIndex]; if (player.skipMonsterPlay) { player.skipMonsterPlay = false; return actionError("Deck Master effect blocks this monster play."); } if (player.monsterPlayed) return actionError("You already played a monster this turn."); if (player.activeMonster) return actionError("You already have an active monster."); const card = getCard(player.hand[handIndex]); if (!card || card.type !== CARD_TYPES.MONSTER) return actionError("Choose a monster card."); player.hand.splice(handIndex, 1); player.activeMonster = makeMonsterInstance(card, state.turnNumber); player.monsterPlayed = true; addMeter(player, 15); addLog(state, `${player.name} summons ${card.name}.`); checkAllAwaken(state); return actionOk(state, `${card.name} summoned.`); }
export function playSpell(state, playerIndex, handIndex) { const turnError = requireTurn(state, playerIndex); if (turnError) return turnError; const player = state.players[playerIndex]; if (player.spellPlayed) return actionError("You already played a spell this turn."); const card = getCard(player.hand[handIndex]); if (!card || card.type !== CARD_TYPES.SPELL) return actionError("Choose a spell card."); const result = resolveSpell(state, playerIndex, card); if (!result.ok) return result; player.hand.splice(handIndex, 1); player.grave.push(card.id); player.spellPlayed = true; addMeter(player, 10); for (const duelist of state.players) duelist.stats.spellsSeen += 1; addLog(state, `${player.name} casts ${card.name}.`); checkAllAwaken(state); checkWinConditions(state); return actionOk(state, `${card.name} resolved.`); }

function resolveSpell(state, playerIndex, card) { const player = state.players[playerIndex]; const foeIndex = opponentIndex(state, playerIndex); const foe = state.players[foeIndex];
  if (card.spellType === "damage") { dealDamage(state, playerIndex, foeIndex, card.value, card.name); return actionOk(state); }
  if (card.spellType === "riskyDamage") { dealDamage(state, playerIndex, foeIndex, card.value, card.name); dealDamage(state, foeIndex, playerIndex, card.selfDamage ?? 200, `${card.name} recoil`); return actionOk(state); }
  if (card.spellType === "heal") { healPlayer(state, playerIndex, card.value); return actionOk(state); }
  if (card.spellType === "shield") { player.shield += card.value; addLog(state, `${player.name} gains a ${card.value} shield.`); return actionOk(state); }
  if (card.spellType === "weaken") { if (!foe.activeMonster) return actionError("The enemy has no active monster."); foe.activeMonster.attack = Math.max(0, foe.activeMonster.attack - card.value); addLog(state, `${getCard(foe.activeMonster.cardId).name} loses ${card.value} ATK.`); return actionOk(state); }
  if (card.spellType === "boost") { if (!player.activeMonster) return actionError("You need an active monster."); player.activeMonster.attack += card.value; player.activeMonster.temporaryAttack += card.value; addLog(state, `${getCard(player.activeMonster.cardId).name} gains ${card.value} ATK this turn.`); return actionOk(state); }
  if (card.spellType === "fortify") { if (player.activeMonster) { player.activeMonster.defense += 300; addLog(state, `${getCard(player.activeMonster.cardId).name} gains 300 DEF.`); } player.shield += card.value; return actionOk(state); }
  if (card.spellType === "mark") { dealDamage(state, playerIndex, foeIndex, card.value, card.name); if (foe.activeMonster) foe.activeMonster.attack = Math.max(0, foe.activeMonster.attack - 200); return actionOk(state); }
  if (card.spellType === "destroyWeak") { if (!foe.activeMonster) return actionError("The enemy has no active monster."); if (foe.activeMonster.attack > card.value) return actionError("Enemy monster is too strong."); destroyMonster(state, foeIndex, `${card.name} shatters ${getCard(foe.activeMonster.cardId).name}.`); addMeter(player, 20); return actionOk(state); }
  if (card.spellType === "skipAttack") { foe.skipAttack = true; addLog(state, `${foe.name}'s next attack is bound by gravity.`); return actionOk(state); }
  if (card.spellType === "meter") { addMeter(player, card.value); return actionOk(state); }
  if (card.spellType === "returnSelf") { if (!player.activeMonster) return actionError("You need an active monster."); player.hand.push(player.activeMonster.cardId); addLog(state, `${getCard(player.activeMonster.cardId).name} returns to ${player.name}'s hand.`); player.activeMonster = null; return actionOk(state); }
  return actionError("Spell has no v1 effect.");
}

export function attack(state, playerIndex) { const turnError = requireTurn(state, playerIndex); if (turnError) return turnError; const player = state.players[playerIndex]; const foeIndex = opponentIndex(state, playerIndex); const foe = state.players[foeIndex]; if (player.skipAttack) { player.skipAttack = false; return actionError("Your next attack was skipped."); } if (player.attacked) return actionError("You already attacked this turn."); if (!player.activeMonster) return actionError("You need an active monster to attack."); const attacker = player.activeMonster; const attackerCard = getCard(attacker.cardId); player.attacked = true;
  if (!foe.activeMonster) { addLog(state, `${attackerCard.name} attacks directly.`); dealDamage(state, playerIndex, foeIndex, attacker.attack, attackerCard.name); checkAllAwaken(state); checkWinConditions(state); return actionOk(state, "Direct attack resolved."); }
  const defender = foe.activeMonster; const defenderCard = getCard(defender.cardId); addLog(state, `${attackerCard.name} attacks ${defenderCard.name}.`);
  if (attacker.attack >= defender.defense) { const overflow = attacker.attack - defender.defense; destroyMonster(state, foeIndex, `${defenderCard.name} is broken in battle.`); addMeter(player, 20); addMeter(foe, 15); if (overflow > 0) dealDamage(state, playerIndex, foeIndex, overflow, attackerCard.name); }
  else { const backlash = defender.defense - attacker.attack; foe.stats.monsterSurvivedAttacks += 1; addMeter(foe, 18); dealDamage(state, foeIndex, playerIndex, backlash, defenderCard.name); addLog(state, `${defenderCard.name} holds firm.`); }
  checkAllAwaken(state); checkWinConditions(state); return actionOk(state, "Attack resolved."); }

export function activateDeckMaster(state, playerIndex) { const turnError = requireTurn(state, playerIndex); if (turnError) return turnError; const player = state.players[playerIndex]; const foe = state.players[opponentIndex(state, playerIndex)]; const master = getMaster(player.deckMasterId); if (!player.masterAwake && player.masterMeter >= 100) player.masterAwake = true; if (!player.masterAwake) return actionError("Deck Master has not awakened."); if (player.masterUsed) return actionError("Deck Master ability was already used.");
  if (master.id === "ember-lion") { if (!player.activeMonster) return actionError("You need an active monster."); player.activeMonster.attack += 700; player.activeMonster.temporaryAttack += 700; }
  if (master.id === "tide-serpent") { healPlayer(state, playerIndex, 800); if (foe.activeMonster) foe.activeMonster.attack = Math.max(0, foe.activeMonster.attack - 300); }
  if (master.id === "iron-golem") player.shield += 1000;
  if (master.id === "star-raven") foe.skipMonsterPlay = true;
  player.masterUsed = true; addLog(state, `${master.name} awakens: ${master.abilityName}!`); return actionOk(state, `${master.abilityName} activated.`); }
export function surrender(state, playerIndex) { state.surrenderedBy = state.players[playerIndex].id; setWinner(state, opponentIndex(state, playerIndex), `${state.players[playerIndex].name} surrendered.`); return actionOk(state, "Surrendered."); }
function destroyMonster(state, playerIndex, message) { const player = state.players[playerIndex]; if (!player.activeMonster) return; player.grave.push(player.activeMonster.cardId); player.activeMonster = null; addLog(state, message); }
function healPlayer(state, playerIndex, amount) { const player = state.players[playerIndex]; const before = player.life; player.life = Math.min(DUEL_CONSTANTS.life, player.life + amount); const healed = player.life - before; player.stats.healedPrevented += healed; addMeter(player, Math.ceil(healed / 100) * 3); addLog(state, `${player.name} heals ${healed} life.`); }
export function dealDamage(state, sourceIndex, targetIndex, amount, sourceName = "damage") { const source = state.players[sourceIndex]; const target = state.players[targetIndex]; let remaining = Math.max(0, Math.floor(amount)); const prevented = Math.min(target.shield, remaining); if (prevented > 0) { target.shield -= prevented; target.stats.healedPrevented += prevented; remaining -= prevented; addMeter(target, Math.ceil(prevented / 100) * 3); addLog(state, `${target.name}'s shield prevents ${prevented} damage.`); } if (remaining <= 0) return 0; target.life = Math.max(0, target.life - remaining); source.stats.damageDealt += remaining; target.stats.damageTaken += remaining; addMeter(source, Math.min(35, Math.ceil(remaining / 100) * 4)); addMeter(target, Math.min(30, Math.ceil(remaining / 100) * 3)); addLog(state, `${sourceName} deals ${remaining} damage to ${target.name}.`); return remaining; }
export function checkAllAwaken(state) { for (const player of state.players) { const master = getMaster(player.deckMasterId); if (!master || player.masterAwake) continue; const condition = master.awakenCondition; const value = player.stats[condition.type] ?? 0; if (value >= condition.amount || player.masterMeter >= 100) { player.masterAwake = true; player.masterMeter = 100; addLog(state, `${master.name} awakens beside ${player.name}.`); } } }
export function checkWinConditions(state) { if (state.winner) return; const defeated = state.players.findIndex((player) => player.life <= 0); if (defeated !== -1) setWinner(state, opponentIndex(state, defeated), `${state.players[defeated].name}'s life reached 0.`); }
function setWinner(state, winnerIndex, reason) { if (state.winner) return; state.winner = { playerId: state.players[winnerIndex].id, name: state.players[winnerIndex].name, reason }; state.status = "complete"; addLog(state, `${state.players[winnerIndex].name} wins. ${reason}`); }

export function legalSummary(state, playerId) { const playerIndex = getPlayerIndex(state, playerId); if (playerIndex === -1) return {}; const player = state.players[playerIndex]; const isTurn = state.current === playerIndex && !state.winner; return { isTurn, canPlayMonster: isTurn && !player.monsterPlayed && !player.activeMonster && !player.skipMonsterPlay && player.hand.some((id) => getCard(id)?.type === CARD_TYPES.MONSTER), canPlaySpell: isTurn && !player.spellPlayed && player.hand.some((id) => getCard(id)?.type === CARD_TYPES.SPELL), canAttack: isTurn && !player.attacked && !!player.activeMonster && !player.skipAttack, canActivateMaster: isTurn && (player.masterAwake || player.masterMeter >= 100) && !player.masterUsed }; }
export function sanitizeDuelForPlayer(state, playerId) { const ownIndex = getPlayerIndex(state, playerId); return { id: state.id, seed: state.seed, status: state.status, turnNumber: state.turnNumber, current: state.current, turnEndsAt: state.turnEndsAt, turnSeconds: state.turnSeconds, winner: state.winner, log: state.log.slice(-18), players: state.players.map((player, index) => sanitizePlayer(player, index === ownIndex)), legal: legalSummary(state, playerId) }; }
export function sanitizePlayer(player, isSelf = false) { const activeCard = player.activeMonster ? getCard(player.activeMonster.cardId) : null; const master = getMaster(player.deckMasterId); return { id: player.id, name: player.name, color: player.color, life: player.life, deckCount: player.deck.length, graveCount: player.grave.length, hand: isSelf ? [...player.hand] : undefined, handCount: player.hand.length, activeMonster: player.activeMonster ? { ...player.activeMonster, name: activeCard?.name, element: activeCard?.element, rarity: activeCard?.rarity } : null, shield: player.shield, monsterPlayed: player.monsterPlayed, spellPlayed: player.spellPlayed, attacked: player.attacked, skipMonsterPlay: player.skipMonsterPlay, skipAttack: player.skipAttack, master: master ? { id: master.id, name: master.name, element: master.element, abilityName: master.abilityName, abilityText: master.abilityText, awakenText: master.awakenText, model: master.model } : null, masterMeter: player.masterMeter, masterAwake: player.masterAwake, masterUsed: player.masterUsed, stats: { ...player.stats }, deckName: player.deckName, connected: player.connected }; }
export function getCardCounts(cardIds) { return cardIds.reduce((counts, id) => { counts[id] = (counts[id] ?? 0) + 1; return counts; }, {}); }
export function createPracticeOpponent() { return { id: "bot", name: "Atrium Bot", color: "#94a3b8", deck: deckFromStarter("ironroot-wall") }; }
export function mastersForSelect() { return DECK_MASTERS.map((master) => ({ id: master.id, name: master.name, style: master.style, element: master.element, abilityName: master.abilityName, abilityText: master.abilityText, awakenText: master.awakenText })); }
